import {
  BOUNDARY_POLICY_ID,
  BUILD_AUTHORITY_LIMITATION,
  BUILD_CLAIM_LIMITATION,
  BUILD_POLICY_ID,
  DATED_SOURCE_URL,
  INTERNAL_DIGEST_LIMITATION,
  REAL_GRAPH_BUILD_POLICY_SCHEMA,
  REAL_GRAPH_INTERMEDIATE_SCHEMA,
  RELEASE_CERTIFICATE_LIMITATION,
  parseRealGraphBuildPolicyJson,
  realGraphBuildPolicyIdentity,
} from './contracts.mjs';
import { FROZEN_RELATIVE_PATHS } from './workspace_paths.mjs';

const policy = {
  schema: REAL_GRAPH_BUILD_POLICY_SCHEMA,
  policyId: BUILD_POLICY_ID,
  dataClassification: 'candidate-private-build-control',
  researchObservedAt: '2026-08-14T07:38:06.307Z',
  source: {
    provider: 'Geofabrik GmbH',
    region: 'pennsylvania',
    providerPageUrl: 'https://download.geofabrik.de/north-america/us/pennsylvania.html',
    datedFileName: 'pennsylvania-260813.osm.pbf',
    datedUrl: DATED_SOURCE_URL,
    sidecarUrl: `${DATED_SOURCE_URL}.md5`,
    clocks: {
      sourceAsOf: '2026-08-13T20:21:01.000Z',
      retrievedAt: null,
      observedAt: null,
      builtAt: null,
    },
    discoveryBinding: {
      providerByteCount: 344_436_627,
      providerMd5: 'c5eb6fea08b4d6ea3ebbb1cc61dd9fbe',
      evidenceClass: 'discovery-only-not-local-authority',
    },
    localPayloadBinding: {
      absolutePath: null,
      sha256: null,
      byteCount: null,
      retrievedAt: null,
      observedAt: null,
      status: 'unavailable',
    },
    admissionStatus: 'candidate-only',
    latestAllowed: false,
    fallbackAllowed: false,
  },
  extractor: {
    recommendation: {
      toolId: 'osmium-tool/1.19.1/win-64/conda-forge-h60971b7_0',
      name: 'osmium-tool',
      version: '1.19.1',
      upstreamRevision: '18ac055a71ffebefb3b7407c0d324e2532770a79',
      upstreamReleaseUrl: 'https://github.com/osmcode/osmium-tool/releases/tag/v1.19.1',
      upstreamReadmeUrl: 'https://raw.githubusercontent.com/osmcode/osmium-tool/v1.19.1/README.md',
      licenceSpdx: 'GPL-3.0-only',
      windowsSupport: 'upstream-tested',
      distribution: {
        channel: 'conda-forge',
        platform: 'win-64',
        packageFilename: 'osmium-tool-1.19.1-h60971b7_0.conda',
        packageSpec: 'osmium-tool=1.19.1=h60971b7_0',
        packageIndexUrl: 'https://anaconda.org/channels/conda-forge/packages/osmium-tool/files',
        installCommandDraft: [
          'conda',
          'create',
          '--prefix',
          '{PRIVATE_TOOL_PREFIX}',
          '--override-channels',
          '--channel',
          'conda-forge',
          '--strict-channel-priority',
          'osmium-tool=1.19.1=h60971b7_0',
        ],
      },
      versionArguments: ['--version'],
      status: 'recommendation-only',
    },
    installedObservation: {
      toolId: 'osmium-tool/1.19.1/win-64/conda-forge-h60971b7_0',
      version: null,
      absolutePackagePath: null,
      packageSha256: null,
      packageByteCount: null,
      packageObservedAt: null,
      absoluteBinaryPath: null,
      versionArguments: ['--version'],
      versionOutput: null,
      binarySha256: null,
      binaryByteCount: null,
      observedAt: null,
      acceptedAt: null,
      status: 'unavailable',
    },
    downloadTransport: {
      toolId: 'curl/supervisor-version-unselected',
      version: null,
      absoluteBinaryPath: null,
      versionArguments: ['--version'],
      versionOutput: null,
      binarySha256: null,
      binaryByteCount: null,
      observedAt: null,
      acceptedAt: null,
      status: 'unavailable',
    },
    alternatives: [
      {
        name: 'pyosmium',
        version: '4.3.1',
        licenceSpdx: 'BSD-2-Clause',
        windowsSupport: 'official-64-bit-wheels',
        referenceUrl: 'https://docs.osmcode.org/pyosmium/v4.3.1/',
        status: 'not-admitted-no-fallback',
        reason: 'It adds a Python runtime and custom handler/parser surface; v2 admits only exact osmium CLI output and a separately reviewed OPL-to-RD-B adapter.',
      },
    ],
  },
  boundary: {
    policyId: BOUNDARY_POLICY_ID,
    coreReference: {
      name: 'City Limits',
      catalogUrl: 'https://opendataphilly.org/datasets/city-limits/',
      geojsonUrl: 'https://hub.arcgis.com/api/v3/datasets/405ec3da942d4e20869d4e1449a2be48_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1',
      serviceItemId: '405ec3da942d4e20869d4e1449a2be48',
      layerId: 0,
      declaredFeatureUpdatedOn: '2012-07-22',
      serviceDataLastEditAt: '2025-10-07T18:23:32.869Z',
      observedAt: '2026-08-14T07:38:06.307Z',
      crs: 'OGC:CRS84',
      geometryTypes: ['Polygon', 'MultiPolygon'],
    },
    localCoreBinding: {
      absolutePath: null,
      sha256: null,
      byteCount: null,
      observedAt: null,
      status: 'unavailable',
    },
    buffer: {
      distance: 1_000,
      unit: 'metre',
      purpose: 'Extraction completeness only; buffer-only geometry is context and never traversable in v2.',
      builderPackage: '@turf/turf',
      builderVersion: '7.3.5',
      builderIntegrity: 'sha512-l5Z1ZFEizN9p5GxX3mzUGf+i4t7AP3YpWcNdf9+kIzJcQD3eYuGBabj2hLrfrluqFJ+uxsuo4RgPtortQ9Dwpg==',
      builderFunction: 'buffer',
      steps: 32,
      outputCrs: 'OGC:CRS84',
      traversable: false,
    },
    localBufferBinding: {
      absolutePath: null,
      sha256: null,
      byteCount: null,
      builtAt: null,
      status: 'unavailable',
    },
    crossState: {
      policy: 'philadelphia-core-only-no-cross-state/v1',
      sourceCoverage: 'dated-geofabrik-pennsylvania-only',
      odEndpointRule: 'both-endpoints-inside-or-on-core-boundary',
      traversableSegmentRule: 'entire-segment-inside-or-on-core-boundary',
      outsideCoreDisposition: 'context-only-not-traversable',
      delawareRiverCrossing: 'unsupported',
      newJerseyCrossing: 'unsupported',
      unsupportedOutcome: 'coverage-unavailable-not-no-route',
    },
    licence: {
      name: 'City of Philadelphia City Limits data',
      catalogLicenceLabel: 'City of Philadelphia License',
      termsUrl: 'https://www.phila.gov/terms-of-use/',
      internalBuildUse: 'candidate-only',
      publicRedistribution: 'legal-review-required',
    },
  },
  intermediate: {
    schema: REAL_GRAPH_INTERMEDIATE_SCHEMA,
    format: 'OPL',
    mediaType: 'text/x-osmium-opl; charset=utf-8',
    formatReferenceUrl: 'https://osmcode.org/opl-file-format/',
    objectOrder: 'nodes-then-ways-then-relations-id-ascending',
    filterExpressions: ['nw/highway', 'wr/route=ferry', 'r/type=restriction'],
    requiredFields: {
      node: ['id', 'version', 'timestamp', 'tags', 'longitude', 'latitude'],
      way: ['id', 'version', 'timestamp', 'tags', 'nodeRefsWithLocations'],
      relation: ['id', 'version', 'timestamp', 'tags', 'members'],
    },
    parserStatus: 'rd-b-exact-adapter-unavailable',
    bridgeStatus: 'separate-reviewed-opl-to-rd-b-bridge-required',
    buildEvidenceStatus: 'trusted-controller-build-evidence-unavailable',
    hiddenParserAllowed: false,
    recordCount: null,
    localBinding: {
      absolutePath: null,
      sha256: null,
      byteCount: null,
      observedAt: null,
      status: 'unavailable',
    },
  },
  acquisitionCommandPlan: [
    {
      stepId: 'download-pbf',
      executableSlot: 'supervisor-admitted-curl',
      argv: [
        '--fail',
        '--silent',
        '--show-error',
        '--proto',
        '=https',
        '--tlsv1.2',
        '--output',
        '{SOURCE_PBF_PARTIAL}',
        DATED_SOURCE_URL,
      ],
      shell: false,
      retry: false,
      fallback: false,
      successExitCodes: [0],
      controllerPostconditions: [
        'Trusted controller atomically consumes the exact acquisition lease nonce once before process start.',
        'Partial and final source slots do not exist and contain no symlink or reparse point before process start.',
        'Controller computes final byte count, SHA-256, retrievedAt, and observedAt before issuing an ObservedPayloadReceipt.',
      ],
    },
  ],
  extractionCommandPlan: [
    {
      stepId: 'source-fileinfo',
      executableSlot: 'supervisor-admitted-osmium',
      argv: ['fileinfo', '--extended', '--json', '{SOURCE_PBF}'],
      shell: false,
      retry: false,
      fallback: false,
      successExitCodes: [0],
    },
    {
      stepId: 'extract-buffer',
      executableSlot: 'supervisor-admitted-osmium',
      argv: [
        'extract',
        '--polygon',
        '{BUFFER_BOUNDARY_GEOJSON}',
        '--strategy',
        'complete_ways',
        '--set-bounds',
        '--fsync',
        '--output',
        '{BUFFER_EXTRACT_PBF}',
        '{SOURCE_PBF}',
      ],
      shell: false,
      retry: false,
      fallback: false,
      successExitCodes: [0],
    },
    {
      stepId: 'filter-walking',
      executableSlot: 'supervisor-admitted-osmium',
      argv: [
        'tags-filter',
        '--fsync',
        '--output',
        '{WALKING_FILTERED_PBF}',
        '{BUFFER_EXTRACT_PBF}',
        'nw/highway',
        'wr/route=ferry',
        'r/type=restriction',
      ],
      shell: false,
      retry: false,
      fallback: false,
      successExitCodes: [0],
    },
    {
      stepId: 'check-references',
      executableSlot: 'supervisor-admitted-osmium',
      argv: ['check-refs', '--check-relations', '{WALKING_FILTERED_PBF}'],
      shell: false,
      retry: false,
      fallback: false,
      successExitCodes: [0],
    },
    {
      stepId: 'write-opl',
      executableSlot: 'supervisor-admitted-osmium',
      argv: [
        'add-locations-to-ways',
        '--keep-untagged-nodes',
        '--fsync',
        '--output-format',
        'opl,add_metadata=version+timestamp',
        '--output',
        '{INTERMEDIATE_OPL}',
        '{WALKING_FILTERED_PBF}',
      ],
      shell: false,
      retry: false,
      fallback: false,
      successExitCodes: [0],
    },
    {
      stepId: 'intermediate-fileinfo',
      executableSlot: 'supervisor-admitted-osmium',
      argv: ['fileinfo', '--extended', '--json', '{INTERMEDIATE_OPL}'],
      shell: false,
      retry: false,
      fallback: false,
      successExitCodes: [0],
    },
  ],
  paths: FROZEN_RELATIVE_PATHS,
  licence: {
    dataLicence: 'ODbL-1.0',
    licenceUrl: 'https://opendatacommons.org/licenses/odbl/1-0/',
    attributionText: 'OpenStreetMap contributors',
    attributionUrl: 'https://www.openstreetmap.org/copyright',
    derivativeDatabaseTreatment: 'conservative-odbl-derivative-database',
    machineReadableOrRebuildRequiredForPublic: true,
    publicReleaseEligible: false,
  },
  network: {
    liveAcquisitionAllowlist: [DATED_SOURCE_URL],
    latestAllowed: false,
    redirectAllowed: false,
    retryAllowed: false,
    fallbackAllowed: false,
    apiAllowed: false,
    overpassAllowed: false,
    tileAllowed: false,
    runtimeNetworkAllowed: false,
    credentialsAllowed: false,
  },
  controller: {
    status: 'not-implemented',
    commandsRunnable: false,
    releaseCertificateExecutable: false,
    trustedControllerObservedAtRequired: true,
    atomicOneShotConsumptionRequired: true,
    symlinkAndReparsePointRejectionRequired: true,
    preExistingOutputRejectionRequired: true,
    exactByteRevalidationRequired: true,
    registryState: 'empty',
    minimumFreeBytes: 5_000_000_000,
    remainingDependencies: [
      'separate-reviewed-acquisition-and-extraction-controller',
      'separate-reviewed-opl-to-rd-b-bridge',
      'trusted-controller-build-evidence-receipt',
    ],
  },
  limitations: [
    BUILD_AUTHORITY_LIMITATION,
    RELEASE_CERTIFICATE_LIMITATION,
    BUILD_CLAIM_LIMITATION,
    INTERNAL_DIGEST_LIMITATION,
  ],
};

export const ROUTE_REAL_GRAPH_BUILD_POLICY_JSON_TEXT = JSON.stringify(policy);
parseRealGraphBuildPolicyJson(ROUTE_REAL_GRAPH_BUILD_POLICY_JSON_TEXT);
export const ROUTE_REAL_GRAPH_BUILD_POLICY_IDENTITY = realGraphBuildPolicyIdentity(
  ROUTE_REAL_GRAPH_BUILD_POLICY_JSON_TEXT,
);
