#!/usr/bin/env node
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium, expect } from '@playwright/test';
import { installDeterministicRoutes } from './support/deterministic_browser_fixture.mjs';

const root = path.resolve('dist');
const manifest = JSON.parse(await readFile(path.join(root, '.vite/manifest.json'), 'utf8'));
const storageChunk = manifest['src/routes_diary/diary_storage.js']?.file;
assert.ok(storageChunk, 'Build with manifest before running this test.');
const privateMarker = 'DIARY_WORKSPACE_PRIVATE_92814';
const requests = [];
const errors = [];
const server = createServer(async (request, response) => {
  try {
    const pathname = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    const file = path.resolve(root, pathname === '/' ? 'index.html' : pathname.slice(1));
    if (!file.startsWith(`${root}${path.sep}`)) { response.writeHead(403).end(); return; }
    const bytes = await readFile(file);
    const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.geojson': 'application/geo+json', '.svg': 'image/svg+xml' };
    response.writeHead(200, { 'content-type': mime[path.extname(file)] || 'application/octet-stream', 'cache-control': 'no-store' });
    response.end(bytes);
  } catch { response.writeHead(404).end(); }
});
let browser;
try {
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const origin = `http://127.0.0.1:${server.address().port}`;
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ locale: 'en-US', timezoneId: 'America/New_York', viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('request', (request) => requests.push(`${request.url()} ${request.postData() || ''}`));
  await installDeterministicRoutes(page);
  await page.goto(origin, { waitUntil: 'domcontentloaded' });
  const diaryButton = page.getByRole('button', { name: 'Diary', exact: true });
  await expect(diaryButton).toBeEnabled();
  await diaryButton.click();
  await expect(page.locator('[data-panel-view="diary"]')).toHaveAttribute('aria-busy', 'false');
  await expect(page.locator('[data-diary-view="history"]')).toBeVisible();
  const snapshot = () => page.evaluate(async (url) => (await import(url)).diaryLocalRepository.snapshot(), `${origin}/${storageChunk}`);
  const editor = page.locator('dialog.diary-editor');
  const saveEditor = async () => {
    await editor.getByRole('button', { name: 'Save on this device', exact: true }).click();
    await expect(editor).toHaveCount(0);
  };
  await page.getByRole('button', { name: 'Record a trip', exact: true }).click();
  await editor.locator('[name="label"]').fill(privateMarker);
  await editor.locator('[name="occurredAt"]').fill('2020-02-10T09:15');
  await editor.locator('[name="score"]').selectOption('4');
  await saveEditor();
  let data = await snapshot();
  assert.equal(data.entries.length, 1);
  const first = data.entries[0];
  assert.equal(first.occurredAt, '2020-02-10T14:15:00.000Z');
  assert.equal(first.routeGeometry, null);
  assert.deepEqual(first.tags, []);
  await page.getByRole('button', { name: 'Reset filters', exact: true }).first().click();
  const row = page.locator(`[data-id="${first.id}"]`);
  await row.locator('summary').click();
  await row.getByRole('button', { name: 'Edit entry', exact: true }).click();
  await editor.locator('[name="notes"]').fill('Edited private note');
  await saveEditor();
  data = await snapshot();
  assert.equal(data.entries.length, 1, 'edit must update rather than duplicate');
  assert.equal(data.entries[0].id, first.id);
  assert.equal(data.entries[0].notes, 'Edited private note');
  await row.locator('summary').click();
  await row.getByRole('button', { name: 'Save as a regular route', exact: true }).click();
  await expect.poll(async () => (await snapshot()).entries[0].favorite).toBe(true);
  await page.locator('.diary-favorites summary').click();
  await expect(page.locator('.diary-favorites button')).toHaveCount(1);
  await page.locator('.diary-favorites button').click();
  await expect(editor.locator('[name="label"]')).toHaveValue(privateMarker);
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
  await row.locator('summary').click();
  await row.getByRole('button', { name: 'Take this route again', exact: true }).click();
  await editor.locator('[name="label"]').fill('Second cycling trip');
  await editor.locator('[name="mode"]').selectOption('bike');
  await editor.locator('[name="score"]').selectOption('5');
  await saveEditor();
  data = await snapshot();
  assert.equal(data.entries.length, 2);
  assert.equal(new Set(data.entries.map((entry) => entry.id)).size, 2);
  await page.locator('[data-diary-focus-target="mode-filter"]').selectOption('bike');
  await expect(page.locator('.diary-history-item')).toHaveCount(1);
  await expect(page.locator('.diary-journal-summary')).toHaveText('1 of 2 trips');
  await page.locator('.diary-insights-toggle').click();
  await expect(page.locator('[data-accessible-chart="diary-trend"] tbody tr')).toHaveCount(1);
  await page.locator('[data-diary-focus-target="search"]').fill('does-not-match');
  await page.locator('[data-diary-focus-target="search"]').press('Enter');
  await expect(page.locator('.diary-history-item')).toHaveCount(0);
  await expect(page.locator('[data-accessible-chart="diary-trend"] tbody tr')).toHaveCount(0);
  await page.getByRole('button', { name: 'Reset filters', exact: true }).first().click();
  await expect(page.locator('.diary-history-item')).toHaveCount(2);
  await page.reload({ waitUntil: 'domcontentloaded' });
  await expect(page.locator('[data-panel-view="diary"]')).toHaveAttribute('aria-busy', 'false');
  assert.equal((await snapshot()).entries.length, 2, 'UI changes must survive reload');

  await page.getByRole('button', { name: 'Live route', exact: true }).click();
  await page.getByRole('button', { name: 'Rate your experience on this route', exact: true }).click();
  await page.getByRole('radio', { name: '4 stars', exact: true }).click();
  await expect.poll(async () => (await snapshot()).drafts.length).toBe(1);
  await page.getByRole('button', { name: 'Close rating dialog', exact: true }).click();
  await page.getByRole('button', { name: 'My routes', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Continue rating', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Export private backup', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Continue rating', exact: true }).click();
  await expect(page.getByRole('radio', { name: '4 stars', exact: true })).toBeChecked();
  await page.getByRole('button', { name: 'Close rating dialog', exact: true }).click();
  await page.getByRole('button', { name: 'My routes', exact: true }).click();
  await page.getByRole('button', { name: 'Discard draft…', exact: true }).click();
  assert.equal((await snapshot()).drafts.length, 1, 'discard requires confirmation');
  await page.getByRole('button', { name: 'Discard this draft', exact: true }).click();
  await expect.poll(async () => (await snapshot()).drafts.length).toBe(0);
  await expect(page.locator('.diary-draft-row')).toHaveCount(0);

  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Record a trip', exact: true }).click();
  await expect(editor).toBeVisible();
  const layout = await editor.evaluate((dialog) => ({ scroll: dialog.scrollWidth, width: dialog.clientWidth, right: dialog.getBoundingClientRect().right, left: dialog.getBoundingClientRect().left }));
  assert.ok(layout.scroll <= layout.width + 1 && layout.left >= 0 && layout.right <= 390, `editor must fit mobile: ${JSON.stringify(layout)}`);
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal((await snapshot()).entries.length, 2, 'cancel must not add a trip');
  const journalLayout = await page.locator('[data-diary-view="history"]').evaluate((node) => ({ scroll: node.scrollWidth, width: node.clientWidth }));
  assert.ok(journalLayout.scroll <= journalLayout.width + 1, `mobile history must not overflow: ${JSON.stringify(journalLayout)}`);
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole('button', { name: 'Record a trip', exact: true }).click();
  const routeGeometry = { type: 'LineString', coordinates: [[-75.1652, 39.9526], [-75.1638, 39.9538]] };
  const routeFile = { name: 'private-route.geojson', mimeType: 'application/geo+json', buffer: Buffer.from(JSON.stringify(routeGeometry)) };
  await editor.locator('input[type="file"]').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{invalid') });
  await expect(editor.getByRole('alert')).toContainText('Cannot read this route');
  assert.equal((await snapshot()).entries.length, 2, 'invalid import must not persist');
  await editor.locator('input[type="file"]').setInputFiles(routeFile);
  await expect(editor.locator('.diary-editor__route')).toContainText('Route attached');
  await editor.locator('[name="label"]').fill('Imported trip');
  await editor.locator('[name="score"]').selectOption('3');
  await saveEditor();
  assert.deepEqual((await snapshot()).entries.find((entry) => entry.label === 'Imported trip').routeGeometry, routeGeometry);
  await page.getByRole('button', { name: 'Crime', exact: true }).click();
  await page.locator('.analysis-hub > summary').click();
  await page.locator('[data-route-corridor-open]').click();
  await page.locator('[data-route-file]').setInputFiles(routeFile);
  await expect(page.locator('[data-route-record-trip]')).toBeEnabled();
  await page.locator('[data-route-record-trip]').click();
  await expect(editor).toBeVisible();
  await editor.locator('[name="label"]').fill('Analysis handoff trip');
  await editor.locator('[name="score"]').selectOption('5');
  await saveEditor();
  await expect(page.locator('[data-route-diary-status]')).toContainText('Trip saved on this device');
  const handedOff = (await snapshot()).entries.find((entry) => entry.label === 'Analysis handoff trip');
  assert.deepEqual(handedOff.routeGeometry, routeGeometry);
  await page.locator('[data-route-close]').click();
  await diaryButton.click();
  await expect(page.locator('[data-panel-view="diary"]')).toHaveAttribute('aria-busy', 'false');
  await expect(page.locator(`[data-id="${handedOff.id}"]`)).toBeVisible();
  await page.locator('.language-switch').click();
  await page.getByRole('button', { name: '记录一次出行', exact: true }).click();
  await expect(editor.getByRole('heading', { name: '记录一次出行', exact: true })).toBeVisible();
  await expect(editor.getByRole('button', { name: '保存到此设备', exact: true })).toBeVisible();
  await expect(editor.getByText('体验标签（可选）', { exact: true })).toBeVisible();
  await editor.getByRole('button', { name: '取消', exact: true }).click();
  await page.locator('.language-switch').click();
  const draftContext = await browser.newContext({ locale: 'en-US', viewport: { width: 1280, height: 900 } });
  const draftPage = await draftContext.newPage();
  await installDeterministicRoutes(draftPage);
  await draftPage.goto(`${origin}/?mode=diary`, { waitUntil: 'domcontentloaded' });
  await expect(draftPage.locator('[data-panel-view="diary"]')).toHaveAttribute('aria-busy', 'false');
  await expect(draftPage.getByRole('button', { name: 'Export private backup', exact: true })).toBeDisabled();
  await draftPage.getByRole('button', { name: 'Live route', exact: true }).click();
  await draftPage.getByRole('button', { name: 'Rate your experience on this route', exact: true }).click();
  await draftPage.getByRole('radio', { name: '4 stars', exact: true }).click();
  await expect.poll(() => draftPage.evaluate(async (url) => (await (await import(url)).diaryLocalRepository.snapshot()).drafts.length, `${origin}/${storageChunk}`)).toBe(1);
  await draftPage.getByRole('button', { name: 'Close rating dialog', exact: true }).click();
  await draftPage.getByRole('button', { name: 'My routes', exact: true }).click();
  await expect(draftPage.locator('.diary-history-item')).toHaveCount(0);
  await expect(draftPage.getByRole('button', { name: 'Export private backup', exact: true })).toBeEnabled();
  await expect(draftPage.getByRole('button', { name: 'Continue rating', exact: true })).toBeVisible();
  await draftContext.close();
  assert.deepEqual(errors, []);
  assert.ok(requests.every((request) => !request.includes(privateMarker)), 'private content must not enter requests');
  console.log(JSON.stringify({ status: 'pass', checks: ['default-entry', 'manual-tagless-trip', 'occurredAt', 'edit-no-duplicate', 'repeat-trip', 'shared-filters', 'reload-persistence', 'draft-resume-discard', 'draft-only-backup-enabled', 'mobile-editor-and-history', 'geojson-valid-invalid', 'analysis-route-handoff', 'bilingual-editor', 'network-privacy'] }));
} catch (error) {
  console.error('Diary browser page errors:', errors);
  throw error;
} finally {
  await browser?.close();
  await new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
}
