import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { homeCompareCitywideReadinessHtml, validateHomeCompareCitywideReadiness } from '../../src/home_compare/citywide_readiness.js';
const sha=(v)=>`sha256:${createHash('sha256').update(v).digest('hex')}`;
const ids=['citygeo-address-locator','opa-current-property','opa-assessment-history','real-estate-transfers','philly311-requests','li-property-history','vacant-property-indicators','philadelphia-reported-crime','vision-zero-hin-2025']; const dimensions=['geocoder_address_resolution','property_current_assessment','assessment_history','transfers','requests_311','li_property_history','vacancy','reported_incidents','hin_road_context'];
function fixture(){return {schema:'engagement-home-compare-citywide-readiness/v1',input:{lifecycle:{schema:'engagement-home-compare-citywide-source-lifecycle/v1',semantic_identity:sha('l'),sha256:sha('lf'),bytes:100},ledger:{schema:'engagement-home-compare-citywide-join-dq/v1',semantic_identity:sha('d'),sha256:sha('ld'),bytes:101}},status:'partial',sources:ids.map((source_id,ordinal)=>({source_id,ordinal,receipt_identity:sha(`r${ordinal}`),status:ordinal===0?'unavailable':ordinal===7?'available':'partial',freshness:{status:'current'},clocks:{source_as_of:null,retrieved_at:null,built_at:null,observed_at:'2026-08-30T00:00:00.000Z'},coverage:{status:'citywide'},dq:{status:'partial',flags:['bounded']},official_source_url:'https://www.phila.gov/',limitations:['Aggregate metadata only.']})),dimensions:ids.map((_,ordinal)=>({dimension:dimensions[ordinal],ordinal,required_source_receipt_identities:[sha(`r${ordinal}`)],source_readiness:ordinal===7?'exact-receipt-ready':ordinal===0?'unavailable':'partial',join_status:ordinal===0?'unavailable':'not-admitted',admission_status:ordinal===0?'unavailable':'not-admitted',reason:ordinal===7?'Exact source-ready but join not admitted.':ordinal===8?'Legacy partial HIN is not raw crash or current safety.':'No address join admitted.',row_availability:'unavailable',value_availability:'unavailable',total:null,available_zero:false,identity:sha(`d${ordinal}`)})),privacy:{aggregate_only:true,address_included:false,coordinates_included:false,source_rows_included:false},authority:{product_authority:false,publication_authority:false,redistribution_authority:false,safety_authority:false,routing_authority:false},limitations:['Local candidate.','No private input.','No authority.'],identity:sha('readiness')};}
test('P5 adapter keeps stable source and dimension order with no authority',()=>{const readiness=fixture();assert.deepEqual(validateHomeCompareCitywideReadiness(readiness),readiness);assert.deepEqual(readiness.sources.map(x=>x.source_id),ids);assert.equal(readiness.dimensions[7].source_readiness,'exact-receipt-ready');assert.match(readiness.dimensions[7].reason,/join not admitted/i);assert.match(readiness.dimensions[8].reason,/not raw crash/i);assert.equal(readiness.authority.safety_authority,false);assert.equal(readiness.authority.routing_authority,false);const reordered=structuredClone(readiness);[reordered.sources[0],reordered.sources[1]]=[reordered.sources[1],reordered.sources[0]];assert.throws(()=>validateHomeCompareCitywideReadiness(reordered),/unsupported/i);});
test('adapter fails closed on unknown fields and render is bilingual, clocked, and non-authoritative',()=>{const readiness=fixture();const hostile=structuredClone(readiness);hostile.sources[0].unknown=true;assert.throws(()=>validateHomeCompareCitywideReadiness(hostile),/unknown|unsupported/i);for(const locale of ['en','zh-CN']){const html=homeCompareCitywideReadinessHtml(readiness,{locale});assert.match(html,/source_as_of|来源/);assert.match(html,/not address-level evidence|不是地址级证据/);assert.match(html,/Why unavailable|为何不可用/);}});
