#!/usr/bin/env node
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

import {
  DEFAULT_ROUTE_GOLDEN_S2_MANIFEST_URL,
  ROUTE_GOLDEN_S2_DENOMINATORS,
  ROUTE_GOLDEN_S2_FIXTURE_SET_VERSION,
  ROUTE_GOLDEN_S2_LEDGER_SCHEMA_VERSION,
  ROUTE_GOLDEN_S2_MANIFEST_SCHEMA_VERSION,
  loadS2GoldenFixtureSet,
  runS2GoldenCases,
  validateS2GoldenManifest,
} from '../lib/route_golden_s2_harness.mjs';
import {
  ROUTE_GOLDEN_S2_EXPANDED_STATE_UNIT,
  ROUTE_GOLDEN_S2_ORACLE_CONTRACT_VERSION,
  enumerateS2GoldenBoundedRoutes,
  solveS2GoldenReference,
} from '../lib/route_golden_s2_oracle.mjs';
import {
  ROUTE_GOLDEN_S2_PRODUCT_ADAPTER_VERSION,
  ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
  createS2GoldenProductionAdapter,
  solveS2GoldenWithProductionSearch,
} from '../lib/route_golden_s2_product_adapter.mjs';

const fixtureSet = await loadS2GoldenFixtureSet();
const byId = new Map(fixtureSet.cases.map(({ fixture }) => [fixture.caseId, fixture]));
const expectedCaseIds = [
  'invalid-requested-k',
  'k1-parity',
  'k-smaller-equal-cost-tie',
  'k-larger-than-available',
  'directed-reverse',
  'self-route',
  'self-route-constrained-unresolved',
  'max-route-edge-count',
  'known-false-alternative',
  'unresolved-evidence',
  'bounded-no-route',
  'bounded-no-eligible',
  'budget-exhaustion',
];

test('S2 manifest versions one inventory and seven independent denominators', () => {
  const { manifest, cases } = fixtureSet;
  assert.equal(manifest.schemaVersion, ROUTE_GOLDEN_S2_MANIFEST_SCHEMA_VERSION);
  assert.equal(manifest.fixtureSetVersion, ROUTE_GOLDEN_S2_FIXTURE_SET_VERSION);
  assert.equal(manifest.oracleContractVersion, ROUTE_GOLDEN_S2_ORACLE_CONTRACT_VERSION);
  assert.deepEqual(manifest.expandedStateUnit, ROUTE_GOLDEN_S2_EXPANDED_STATE_UNIT);
  assert.deepEqual(ROUTE_GOLDEN_S2_DENOMINATORS, [
    'conformance', 'primary', 'terminals', 'alternatives', 'constraints', 'budget',
    'completeness',
  ]);
  assert.deepEqual(cases.map(({ fixture }) => fixture.caseId), expectedCaseIds);
  assert.deepEqual(manifest.expectedCounts, {
    conformance: 1,
    primary: 6,
    terminals: 7,
    alternatives: 6,
    constraints: 4,
    budget: 1,
    completeness: 12,
    totalCases: 13,
  });
});

test('manifest rejects duplicate cases, unknown cohort members, count drift, and path escape', () => {
  const duplicate = structuredClone(fixtureSet.manifest);
  duplicate.cases[1].caseId = duplicate.cases[0].caseId;
  assert.throws(() => validateS2GoldenManifest(duplicate),
    (error) => error.code === 'manifest-case-id-duplicate');

  const unknown = structuredClone(fixtureSet.manifest);
  unknown.cohorts.primary[0] = 'not-a-case';
  assert.throws(() => validateS2GoldenManifest(unknown),
    (error) => error.code === 'manifest-cohort-case-missing');

  const countDrift = structuredClone(fixtureSet.manifest);
  countDrift.expectedCounts.completeness -= 1;
  assert.throws(() => validateS2GoldenManifest(countDrift),
    (error) => error.code === 'manifest-count-mismatch');

  const escaped = structuredClone(fixtureSet.manifest);
  escaped.cases[0].file = '../outside.json';
  assert.throws(() => validateS2GoldenManifest(escaped),
    (error) => error.code === 'fixture-path-invalid');
});

test('every checked-in expected result is independently regenerated by exhaustive enumeration', () => {
  for (const { fixture } of fixtureSet.cases) {
    assert.deepEqual(solveS2GoldenReference(fixture.input), fixture.expected, fixture.caseId);
  }
  assert.equal(new URL(DEFAULT_ROUTE_GOLDEN_S2_MANIFEST_URL).protocol, 'file:');
});

test('exhaustive oracle sees all routes while K comparison uses only the ordered prefix', () => {
  const fixture = byId.get('k-smaller-equal-cost-tie');
  const universe = enumerateS2GoldenBoundedRoutes(fixture.input);
  assert.deepEqual(universe.map(({ edgeIds }) => edgeIds), [
    ['a-first', 'a-last'],
    ['b-direct'],
    ['c-first', 'c-last'],
  ]);
  assert.deepEqual(fixture.expected.routes.map(({ edgeIds }) => edgeIds), [
    ['a-first', 'a-last'],
    ['b-direct'],
  ]);
  assert.equal(fixture.expected.search.completeness.routeSearch, 'not-proven');
});

test('oracle result is independent of graph input order and does not mutate fixture input', () => {
  const fixture = byId.get('k-smaller-equal-cost-tie');
  const original = structuredClone(fixture.input);
  const permuted = structuredClone(fixture.input);
  permuted.graph.nodes.reverse();
  permuted.graph.edges.reverse();
  assert.deepEqual(solveS2GoldenReference(permuted), fixture.expected);
  assert.deepEqual(fixture.input, original);
});

test('self-route capability is unresolved rather than vacuously observed true', () => {
  const unconstrained = byId.get('self-route').expected;
  assert.deepEqual(unconstrained.routes[0].edgeIds, []);
  assert.equal(unconstrained.termination, 'requested-candidate-count-reached');
  assert.equal(unconstrained.search.expandedStateCount, 0);

  const constrained = byId.get('self-route-constrained-unresolved').expected;
  assert.equal(constrained.termination, 'unresolved-constraint-evidence');
  assert.deepEqual(constrained.routes, []);
  assert.equal(constrained.search.candidateCount, 0);
  assert.equal(constrained.search.expandedStateCount, 0);
  assert.equal(constrained.search.constraintOutcome, 'unresolved-evidence');
});

test('thin product adapter forwards one graph, request, and evidence without editing result routes', async () => {
  const fixture = byId.get('known-false-alternative');
  let captured;
  const marker = Object.freeze({ marker: 'exact-product-result' });
  const adapter = createS2GoldenProductionAdapter({
    searchProduct(...args) {
      captured = structuredClone(args);
      return marker;
    },
  });
  assert.equal(await adapter(fixture.input), marker);
  assert.equal(captured.length, 3);
  assert.equal(captured[0].graphId, fixture.input.graph.graphId);
  assert.deepEqual(captured[1], fixture.input.request);
  assert.deepEqual(captured[2], fixture.input.edgeObservationsByEdgeId);
});

test('production expanded-state unit exactly matches the independently recorded contract', () => {
  assert.deepEqual(
    ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
    ROUTE_GOLDEN_S2_EXPANDED_STATE_UNIT,
  );
  assert.equal(Object.isFrozen(ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT), true);
});

test('production search matches all independent fixtures and denominators', async () => {
  const ledger = await productionLedger();
  assert.equal(ledger.schemaVersion, ROUTE_GOLDEN_S2_LEDGER_SCHEMA_VERSION);
  assert.equal(ledger.entries.length, 13);
  assert.equal(ledger.summary.terminalLedgerEntries, 13);
  assert.equal(ledger.summary.passedCases, 13);
  assert.equal(ledger.summary.failedCases, 0);
  assert.equal(ledger.entries.every(({ checks }) => (
    checks.fixtureIntegrity === 'pass'
    && checks.byteDeterminism === 'pass'
    && checks.solverContract === 'pass'
  )), true);
  for (const [denominator, expected] of Object.entries(fixtureSet.manifest.expectedCounts)) {
    if (denominator === 'totalCases') continue;
    assert.deepEqual(ledger.summary.denominators[denominator], {
      denominator: expected,
      passed: expected,
      failed: 0,
    });
  }
});

test('ledger keeps non-member denominators not-applicable and never mixes their counts', async () => {
  const ledger = await productionLedger();
  for (const entry of ledger.entries) {
    for (const denominator of ROUTE_GOLDEN_S2_DENOMINATORS) {
      if (!entry.cohorts.includes(denominator)) {
        assert.equal(entry.checks[denominator], 'not-applicable', `${entry.caseId}:${denominator}`);
      }
    }
  }
  const conformance = ledgerEntry(ledger, 'invalid-requested-k');
  assert.deepEqual(conformance.cohorts, ['conformance']);
  assert.equal(conformance.checks.terminals, 'not-applicable');
  assert.equal(conformance.checks.completeness, 'not-applicable');
});

test('two different result byte streams are classified nondeterministic', async () => {
  let targetRun = 0;
  const ledger = await runS2GoldenCases({
    solverId: 'alternating-s2-adapter',
    expandedStateUnit: ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
    async solve(input) {
      const result = structuredClone(await solveS2GoldenWithProductionSearch(input));
      if (input.request?.requestId === 'k1-parity-request') {
        targetRun += 1;
        result.candidateSet.candidateSetId = targetRun % 2 ? 'alternating-one' : 'alternating-two';
      }
      return result;
    },
  });
  const entry = ledgerEntry(ledger, 'k1-parity');
  assert.equal(entry.checks.byteDeterminism, 'fail');
  assert.equal(entry.failureClasses.includes('nondeterministic-bytes'), true);
});

test('fixture load failure becomes one ledger entry and later fixtures still run', async () => {
  const ledger = await runS2GoldenCases({
    solve: solveS2GoldenWithProductionSearch,
    solverId: 'fixture-load-failure-s2-adapter',
    expandedStateUnit: ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
    async loadJson(url) {
      if (url.pathname.endsWith('/invalid-requested-k.json')) {
        throw new Error('synthetic fixture read failure');
      }
      return JSON.parse(await readFile(url, 'utf8'));
    },
  });
  assert.equal(ledger.entries.length, 13);
  assert.deepEqual(ledgerEntry(ledger, 'invalid-requested-k').failureClasses, [
    'fixture-load-error',
  ]);
  assert.equal(ledgerEntry(ledger, 'k1-parity').verdict, 'pass');
});

test('accessor fixture is rejected without executing its getter and later fixtures continue', async () => {
  let getterCalls = 0;
  const ledger = await runS2GoldenCases({
    solve: solveS2GoldenWithProductionSearch,
    solverId: 'accessor-fixture-s2-adapter',
    expandedStateUnit: ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
    async loadJson(url) {
      const value = JSON.parse(await readFile(url, 'utf8'));
      if (url.pathname.endsWith('/invalid-requested-k.json')) {
        Object.defineProperty(value, 'expected', {
          enumerable: true,
          get() {
            getterCalls += 1;
            throw new Error('must not execute');
          },
        });
      }
      return value;
    },
  });
  assert.equal(getterCalls, 0);
  assert.deepEqual(ledgerEntry(ledger, 'invalid-requested-k').failureClasses, ['fixture-invalid']);
  assert.equal(ledgerEntry(ledger, 'k1-parity').verdict, 'pass');
});

test('invalid public result fails closed instead of being repaired by the harness', async () => {
  const ledger = await runS2GoldenCases({
    solverId: 'invalid-result-s2-adapter',
    expandedStateUnit: ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
    async solve(input) {
      const result = structuredClone(await solveS2GoldenWithProductionSearch(input));
      if (input.request?.requestId === 'k1-parity-request') {
        result.candidateSet.candidateIds[0] = 'wrong-candidate-id';
      }
      return result;
    },
  });
  const entry = ledgerEntry(ledger, 'k1-parity');
  assert.equal(entry.checks.solverContract, 'fail');
  assert.equal(entry.failureClasses.includes('solver-result-contract-invalid'), true);
});

test('wrong product expansion-unit evidence fails only the budget denominator', async () => {
  const wrongUnit = {
    ...ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
    includes: 'invented-unit',
  };
  const ledger = await runS2GoldenCases({
    solve: solveS2GoldenWithProductionSearch,
    solverId: 'wrong-expanded-unit-s2-adapter',
    expandedStateUnit: wrongUnit,
  });
  const budget = ledgerEntry(ledger, 'budget-exhaustion');
  assert.equal(budget.checks.budget, 'fail');
  assert.equal(budget.checks.primary, 'pass');
  assert.equal(budget.checks.alternatives, 'pass');
  assert.equal(budget.checks.completeness, 'pass');
});

async function productionLedger() {
  return runS2GoldenCases({
    solve: solveS2GoldenWithProductionSearch,
    solverId: ROUTE_GOLDEN_S2_PRODUCT_ADAPTER_VERSION,
    expandedStateUnit: ROUTE_GOLDEN_S2_PRODUCT_EXPANDED_STATE_UNIT,
  });
}

function ledgerEntry(ledger, caseId) {
  const entry = ledger.entries.find((candidate) => candidate.caseId === caseId);
  assert.ok(entry, `Missing S2 Golden ledger entry: ${caseId}`);
  return entry;
}
