import { escapeHtml } from './view.js';

export const HOME_COMPARE_CITYWIDE_READINESS_SCHEMA = 'engagement-home-compare-citywide-readiness/v1';
const SHA = /^sha256:[a-f0-9]{64}$/;
const AUTHORITY = JSON.stringify({ product_authority:false, publication_authority:false, redistribution_authority:false, safety_authority:false, routing_authority:false });
const SOURCE_IDS = ['citygeo-address-locator','opa-current-property','opa-assessment-history','real-estate-transfers','philly311-requests','li-property-history','vacant-property-indicators','philadelphia-reported-crime','vision-zero-hin-2025'];
const DIMENSIONS = ['geocoder_address_resolution','property_current_assessment','assessment_history','transfers','requests_311','li_property_history','vacancy','reported_incidents','hin_road_context'];
export async function loadHomeCompareCitywideReadiness({ request = fetchJson, url = 'data/home_compare_citywide_readiness.v1.json', signal } = {}) { return validateHomeCompareCitywideReadiness(await request(url, { signal, cache: 'no-store' })); }
export function validateHomeCompareCitywideReadiness(value) {
  exact(value, ['schema','input','status','sources','dimensions','privacy','authority','limitations','identity'], 'readiness artifact');
  if (value.schema !== HOME_COMPARE_CITYWIDE_READINESS_SCHEMA || value.input?.lifecycle?.schema!=='engagement-home-compare-citywide-source-lifecycle/v1' || value.input?.ledger?.schema!=='engagement-home-compare-citywide-join-dq/v1' || !['partial','unavailable'].includes(value.status) || !SHA.test(value.identity || '') || !Array.isArray(value.sources) || value.sources.length !== 9 || !Array.isArray(value.dimensions) || value.dimensions.length !== 9 || JSON.stringify(value.authority) !== AUTHORITY || value.privacy?.aggregate_only !== true || value.privacy?.address_included !== false || value.privacy?.coordinates_included !== false || value.privacy?.source_rows_included !== false) throw new Error('Readiness artifact is unsupported or violates the non-authoritative privacy boundary.');
  for (const [index, source] of value.sources.entries()) { exact(source,['source_id','ordinal','receipt_identity','status','freshness','clocks','coverage','dq','official_source_url','limitations'],`readiness source ${index}`); if(source.source_id!==SOURCE_IDS[index] || source.ordinal!==index || !SHA.test(source.receipt_identity||'') || !['available','available-zero','partial','unavailable'].includes(source.status) || !/^https:\/\//.test(source.official_source_url) || !Array.isArray(source.limitations) || !source.freshness?.status || !source.clocks || !source.coverage?.status || !source.dq?.status) throw new Error('Readiness source is unsupported.'); }
  for (const [index, dimension] of value.dimensions.entries()) { if (dimension.dimension!==DIMENSIONS[index] || dimension.ordinal !== index || dimension.required_source_receipt_identities?.[0]!==value.sources[index].receipt_identity || !SHA.test(dimension.identity || '') || !['exact-receipt-ready','partial','unavailable'].includes(dimension.source_readiness) || !['not-admitted','partial','unavailable'].includes(dimension.join_status) || dimension.total !== null || dimension.available_zero !== false || dimension.row_availability !== 'unavailable' || dimension.value_availability !== 'unavailable') throw new Error('Readiness dimension is unsupported or fail-open.'); }
  return Object.freeze(structuredClone(value));
}
export function homeCompareCitywideReadinessHtml(readiness, { locale = 'en' } = {}) {
  const zh = locale === 'zh-CN'; const copy = zh ? { title:'全市来源就绪度', candidate:'本地、非权威候选；不是地址级证据。', source:'来源', dimension:'维度', clocks:'时钟', coverage:'覆盖 / DQ', why:'为何不可用或未准入', authority:'不授权产品、发布、再分发、安全、路由、通勤时间或等时圈。', missing:'本地 readiness 产物不可用；请生成并追踪 citywide lifecycle、join/DQ 与 readiness 产物。' } : { title:'Citywide source readiness', candidate:'Local non-authoritative candidate; not address-level evidence.', source:'Source', dimension:'Dimension', clocks:'Clocks', coverage:'Coverage / DQ', why:'Why unavailable or not admitted', authority:'Does not authorize product, publication, redistribution, safety, routing, travel time, or isochrones.', missing:'Local readiness artifact is unavailable; generate and track the citywide lifecycle, join/DQ, and readiness artifact.' };
  if (!readiness) return `<section class="home-compare__readiness" data-home-citywide-readiness data-readiness-status="unavailable"><h3>${escapeHtml(copy.title)}</h3><p>${escapeHtml(copy.missing)}</p></section>`;
  return `<section class="home-compare__readiness" data-home-citywide-readiness data-readiness-status="${escapeHtml(readiness.status)}"><h3>${escapeHtml(copy.title)}</h3><p><strong>${escapeHtml(copy.candidate)}</strong> ${escapeHtml(copy.authority)}</p><details><summary>${escapeHtml(copy.source)} (9)</summary><div class="home-compare__readiness-list">${readiness.sources.map(s=>`<article><h4>${escapeHtml(s.source_id)} · ${escapeHtml(s.status)}</h4><p><a href="${escapeHtml(s.official_source_url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(copy.source)}</a></p><p><strong>${escapeHtml(copy.clocks)}:</strong> ${escapeHtml(clockText(s.clocks))}</p><p><strong>${escapeHtml(copy.coverage)}:</strong> ${escapeHtml(`${s.coverage.status}; ${s.dq.status}; ${s.freshness.status}`)}</p><p>${escapeHtml(s.limitations.join(' '))}</p></article>`).join('')}</div></details><details><summary>${escapeHtml(copy.dimension)} (9)</summary><div class="home-compare__readiness-list">${readiness.dimensions.map(d=>`<article><h4>${escapeHtml(d.dimension)}</h4><p>${escapeHtml(`${d.source_readiness}; join ${d.join_status}; admission ${d.admission_status}`)}</p><p><strong>${escapeHtml(copy.why)}:</strong> ${escapeHtml(d.reason)}</p></article>`).join('')}</div></details></section>`;
}
function fetchJson(url, options){return fetch(url,options).then(r=>{if(!r.ok)throw new Error(`Readiness request failed: ${r.status}`);return r.json()})} function clockText(c){return ['source_as_of','retrieved_at','built_at','observed_at'].map(k=>`${k}: ${c[k]||'unavailable'}`).join(' · ')} function exact(v,k,l){if(!v||typeof v!=='object'||Array.isArray(v)||JSON.stringify(Object.keys(v).sort())!==JSON.stringify([...k].sort()))throw new Error(`${l} contains unknown or missing fields.`)}
